In [29]:
import pandas as pd

# filepath to CLEANED need data
#filepath = 'https://raw.githubusercontent.com/LondonEnergyMap/cleandata/master/epc_domestic_ldn.csv'
#filepath = 'http://raw.githubusercontent.com/LondonEnergyMap/cleandata/master/epc_domestic_ldn.csv'
filepath = 'epc_domestic_ldn.csv'

# read csv into dataframe
df_all = pd.read_csv(filepath)

# drop first column 
df_all.drop(columns = 'Unnamed: 0', inplace=True)
df_all.head()

/Users/dora/miniconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (51,52,60,61,80) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,key,add1,add2,add3,pcode,bref,curr_enr,poten_enr,curr_eff,poten_eff,...,corridor,unhcorridor,fheight,pv,solarwtr,mechvent,addfull,localauth,constit,certificateh
0,144129020080916070948,Flat 109 Thomas More House,Barbican,NaN,EC2Y 8BU,3313370568,E,E,49,51,...,unheated corridor,9.0,2.0,0,N,natural,"Flat 109 Thomas More House, Barbican",City of London,Cities of London and Westminster,bad6f7ac443f6b99a86099842248a4aae05dd339695f60...
1,61487520080112090145,"Apartment 73, Globe View","10, High Timber Street",NaN,EC4V 3PQ,6648304468,B,B,84,85,...,heated corridor,0.0,2.0,0,N,natural,"Apartment 73, Globe View, 10, High Timber Street",City of London,Cities of London and Westminster,94d684331e6415c5951eea56483d6ad2c09ddc4cf13cd0...
2,59284520080108050155,Flat 214 Queens Quay,"58, Upper Thames Street",NaN,EC4V 3EJ,6499404468,E,D,40,59,...,heated corridor,0.0,2.0,0,N,natural,"Flat 214 Queens Quay, 58, Upper Thames Street",City of London,Cities of London and Westminster,2786fcb2bf3ce2cee971352639700b1f2d86b66f8e1993...
3,63505720080123070156,Flat 7,"26-27, Great Tower Street",NaN,EC3R 5AQ,3039034468,D,D,61,67,...,unheated corridor,12.0,3.0,0,N,natural,"Flat 7, 26-27, Great Tower Street",City of London,Cities of London and Westminster,cf503404c6b12dc0e13e9c260270bf4c21b00173a6ad70...
4,62934020080121090118,Flat 721,Willoughby House,Barbican,EC2Y 8BN,9021724468,C,B,78,81,...,heated corridor,0.0,2.0,0,N,natural,"Flat 721, Willoughby House, Barbican",City of London,Cities of London and Westminster,857681feb34bdb9a586728ff9e89da3b42e826f214016f...

In [33]:
def changetypes(df, df_dict):
    # reduce dataframe size by changing column types
    # change to category
    cat = [6, 10, 11, 17, 32, 33, 34, 35, 39, 40, 47, 48, 50,51, 53,54, 56,57, 59,60, 62,63, 65,66, 68,69, 71,72, 75, 79, 80]
    for i in range(len(cat)):
        tempcol = df_dict[cat[i]]
        df[tempcol] = df[tempcol].astype('category')

    # change to float32
    floatlist = [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 76, 77]
    for i in range(len(floatlist)):
        tempcol = df_dict[floatlist[i]]
        df[tempcol] = df[tempcol].astype('float32')

    # change to int32
    intlist = [8, 18, 19, 20, 21]
    for i in range(len(intlist)):
        tempcol = df_dict[intlist[i]]
        df[tempcol] = df[tempcol].astype('int32')

    # change from floating to int32
    f2int = [36, 38, 41, 42, 43, 44, 45, 74, 78] #winturbine(74) use -100?

    # cannot convert float to int if there are missing values, so first convert NaN to -1
    for i in range(len(f2int)):
        tempcol = df_dict[f2int[i]]
        df[tempcol].fillna(-1, inplace=True)
        df[tempcol] = df[tempcol].astype('int32')
    return df

In [34]:
# change datatypes to minimise memory
df_dict = df.columns
df = changetypes(df_all, df_dict)
df.dtypes

key                  object
add1                 object
add2                 object
add3                 object
pcode                object
bref                  int64
curr_enr           category
poten_enr            object
curr_eff              int32
poten_eff             int64
prop_type          category
builtform          category
insp_date            object
localauth_code       object
constit_code         object
county               object
lodge_date           object
transact_type      category
curr_envirr           int32
poten_envirr          int32
curr_encons           int32
poten_encons          int32
curr_co2            float32
curr_co2perarea     float32
poten_co2           float32
curr_light          float32
poten_light         float32
curr_heatcost       float32
poten_heatcost      float32
curr_hotwtr         float32
                     ...
wall                 object
wall_eff           category
wall_enveff        category
heat2                object
heat2_eff          category
heat2_enveff       category
roof                 object
roof_eff           category
roof_enveff        category
heat                 object
heat_eff           category
heat_enveff        category
control              object
control_eff        category
control_enveff     category
light                object
light_eff          category
light_enveff       category
mainfuel             object
windt                 int32
corridor           category
unhcorridor         float32
fheight             float32
pv                    int32
solarwtr           category
mechvent           category
addfull              object
localauth            object
constit              object
certificateh         object
Length: 85, dtype: object

In [37]:
df.pcode.head()

0    EC2Y 8BU
1    EC4V 3PQ
2    EC4V 3EJ
3    EC3R 5AQ
4    EC2Y 8BN
Name: pcode, dtype: object

In [40]:
filepath2 = 'http://raw.githubusercontent.com/LondonEnergyMap/rawdata/master/consumption_postcode/gas/Postcode_level_gas_estimates_2015_experimental.csv'

df_pcode = pd.read_csv(filepath2)
df_pcode.head()

   POSTCODE   CONSUMPTION  METER_COUNT          MEAN        MEDIAN
0       AB1  4.839871e+06          260  18614.886582  13138.500000
1   AB1 6WD  4.344600e+04            7   6206.571429   6477.000000
2      AB10  7.062027e+06          346  20410.481800  15476.000000
3  AB10 1AU  6.718056e+04           12   5598.380162   4586.223984
4  AB10 1BA  2.500300e+05           14  17859.283874  11501.486620